### ISSUE TITLE
Recommendation from Flutter Slack Channel

### ISSUE THREAD

**Issue by AbhishekDoshi26** [Ishchik/delivery_app#1]
Hey there! Here are some points I went through:

- Update README.md
- Remove google-services.json file as it contains some serious important data which can be used to get into your firebase account

**Comment by Ishchik** [comment]
How should i hide it from others meanwhile keep it working after `git clone ` on other pc? Or where should i look for a solution?

**Comment by AbhishekDoshi26** [comment]
You can keep it in your local PC or local repo. Just don't `git add` when pushing to github

**Comment by AbhishekDoshi26** [comment]
if someone clone's your repo and runs in their PC, they will be able to update your Firebase collections and documents. `google-services.json` gives them permission to read/write into <b>your</b> firebase account

**Comment by Ishchik** [comment]
I think i've got you right. So i just have to update my `.gitignore` file to ignore `google-services.json`

**Comment by AbhishekDoshi26** [comment]
Yes.

Abhishek Doshi

**Comment by Ishchik** [comment]
Many thanks!
Will update it soon
